### PR TITLE
Uncomment chatlogs

### PR DESCRIPTION
**Pull request by TrayHard**

### CODE REVIEW

**Comment by bartrpe** [comment]
merg!!!

**Comment by bartrpe** [comment]
@videoP merg!!!!!!!!!!

**Comment by TrayHard** [comment]
foreal…(

**Comment by bartrpe** [comment]
MEEEEEEEEEEEEERG

**Comment by TrayHard** [comment]
PLEASE!

**Comment by Formosan** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA



THIS IS PAIN

EXISTENCE IS PAIN


MERGE OR I'LL DIE!!!

**Comment by fellfalafel** [comment]
**MERG!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!**

john paul the second ****** little children 😭😭😭😭😭

**Comment by TrayHard** [comment]
JUST DO IT, WE NEED LOGS!

**Comment by bartrpe** [comment]
@videoP 😭😭😭😭

**Comment by TrayHard** [comment]
LETS MAKE A RIOT GUYS!

**Comment by bartrpe** [comment]
pleaaase

**Comment by sithmartyr** [comment]
loda doesn't work for free

**Review by videoP — APPROVED** [review]

**Comment by TrayHard** [comment]
Guys I exchanged my translation services ru->eng for this merge, we finally did it, thanks to all supporters, am glad we did it!

**Comment by bartrpe** [comment]
YEEEES
YEEEEEEEEEEEEESSSSSSSS

**Pull request merged**
